version: "3"
services:
  api1:
    build:
      context: ./api1
      dockerfile: Dockerfile
    container_name: api1
    restart: always
    env_file: .env
    environment:
      - ENV=development
    ports:
      - 3030:3030
    volumes:
      - "./api1:/usr/src/api1"
      - "/usr/src/api1/node_modules"
      - "/usr/src/api1/dist"
