FROM node:16-alpine

WORKDIR /usr/src/api1

COPY *.* ./

RUN yarn global add @nestjs/cli

RUN yarn global add pm2

RUN yarn install --frozen-lockfile --network-timeout 600000

RUN yarn build

COPY . .

CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]